### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by dabit3** [TheGraphAcademy/Graph-Academy-Hub#5]
Minor typo at https://thegraph.academy/developers/defining-a-subgraph/

"dataSources.mapping.blockHandlers: Defines of the blocks your subgraph next to"

Maybe should be:

"dataSources.mapping.blockHandlers: Defines the blocks your subgraph talks to"

I tried to find this in the codebase to submit a PR myself but could not find it.

<img width="824" alt="Screen Shot 2021-04-06 at 10 12 35 PM" src="https://user-images.githubusercontent.com/1857282/113805087-73f5ba00-9725-11eb-90c0-68d29359b4d3.png">

Loving all of the great content and tutorials, awesome stuff!

**Comment by TheGraphAcademy** [comment]
Thanks Nader for highlighting the error. It's corrected now.

Stefan
